kubewarden/policy-server

- .dockerignore
- .github/workflows/container-image.yml
- Dockerfile
Add a Dockerfile and Github Action workflow to build an image and
publish it on Github Container Registry.
Fixes #6
> Build and publish images

- src/main.rs
- src/worker.rs
Wait for all the workers to be ready before we start serving the web API.
Bootstraping the workers can take some time, depending on their number and the amount of policies each one of them has to initialize.
> Do not start the web API until the workers are ready

- .github/workflows/container-image.yml
- .github/workflows/testdrive-release.yml
- Cargo.toml
- Dockerfile
- README.md
- crates/policy-evaluator/Cargo.toml
- crates/policy-evaluator/src/policy.rs
- crates/policy-evaluator/src/policy_evaluator.rs
- crates/policy-evaluator/src/validation_response.rs
- crates/policy-testdrive/README.md
- crates/policy-testdrive/src/cli.rs
- policies.yml.example
- src/main.rs
> Rename from chimera -> kubewarden

- Dockerfile
The resulting image will also be based on OpenSUSE Leap 15.3.
> Use openSUSE Leap 15.3 to build the policy-server

- Cargo.lock
- Cargo.toml
Fixes: https://github.com/kubewarden/policy-server/issues/67
Fixes: https://github.com/kubewarden/policy-server/issues/68
> Bump dependencies in security report

- Cargo.lock
- Cargo.toml
- src/main.rs
Related: https://github.com/kubewarden/kwctl/issues/40
> implement context aware policies refresh on the policy-server side

- Cargo.lock
- Cargo.toml
Tag release 0.2.0 of policy-server. This is the first release
of policy server that can handle Rego-based policies too.
> feat: Handle policies written using Rego

- src/metrics/mod.rs
- src/metrics/policy_evaluations_latency.rs
- src/metrics/policy_evaluations_total.rs
- src/worker.rs
Adds a metric to allow the operator check how long a policy evaluation takes.
> Policy evaluation latency metric.

- kubewarden-dashboard.json
Adds three more panels using the latest metrics added in Kubewarden. The metrics are the policy counter and policy evaluation latency metrics.
> New Grafana panel using other Kubewarden metrics.

- Cargo.toml
- src/cli.rs
> Fix a deprecation warning generated by Clap

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/main.rs
- src/policy_downloader.rs
Depends on: https://github.com/kubewarden/policy-evaluator/pull/108
Fixes: https://github.com/kubewarden/policy-server/issues/220
> Make verification config truly optional

- Cargo.lock
- Cargo.toml
Update to latest version of policy-evaluator.
> Relase 0.3.2

- src/worker.rs
Policies running in monitor mode were still rejecting request if the policies mutate the request. This commit changes the policy-server code to always accept request in monitor mode. Regardless of the request of the evaluation for the income request.
Fixes https://github.com/kubewarden/policy-server/issues/260
1. Install [kubewarden-defaults](https://github.com/kubewarden/helm-charts/tree/main/charts/kubewarden-defaults) with mode: monitor and mutating: false
2. Attempt to create a non-privileged pod
3. The creation will be rejected
> fix: policies in monitor mode still rejecting requests.

- Cargo.lock
- Cargo.toml
> Tag v1.0.0 release

- Cargo.lock
- Cargo.toml
Relates https://github.com/kubewarden/policy-sdk-rust/issues/40
Relates https://github.com/kubewarden/policy-sdk-rust/issues/41
> deps: Consume policy-evaluator v0.4.4

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/main.rs
- src/policy_downloader.rs
>  feat: use docker_credential crate instead of DockerConfig

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> Bump version v1.1.2

- .github/workflows/container-image.yml
Adds steps in the container image release process to generate the SBOM file for it and upload it to the build artifacts and as a release asset. 
Fix #314
> Container image SBOM

- CHANGELOG.md
- Cargo.toml
Prepare for a new release of the Kubewarden stack
> Create 1.3.0-rc1 release

- CHANGELOG.md
- Cargo.toml
> v1.3.0-rc3 release

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
> Create v1.3.0 release

- Cargo.toml
> chore: upgrade rust edition

- .github/workflows/tests.yml
- Cargo.lock
- Cargo.toml
- Makefile
- e2e-tests/.gitignore
- e2e-tests/01-setup.yml
- e2e-tests/02-monitor-and-protect-modes.yml
- e2e-tests/03-audit-endpoint.yml
- e2e-tests/04-timeout-protection.yml
- e2e-tests/99-teardown.yml
- e2e-tests/Makefile
- e2e-tests/e2e-tests-policies/.gitignore
- e2e-tests/test_data/pod_sleep_100ms.json
- e2e-tests/test_data/pod_sleep_4s.json
- e2e-tests/test_data/pod_with_privileged_containers.json
- e2e-tests/test_data/policies.yaml
- src/cli.rs
- src/main.rs
- src/worker.rs
- src/worker_pool.rs
> This supersedes https://github.com/kubewarden/policy-server/pull/389 which was accidentally merged and then got reverted
Ensure a policy cannot run more than a given amount of time.
This is required to fix https://github.com/kubewarden/policy-server/issues/254
Note 1: this PR builds on top of https://github.com/kubewarden/policy-server/pull/388 to ensure all the tests are passing
Note 2: this PR depends on https://github.com/kubewarden/policy-evaluator/pull/224
> Feat policy timeout protection

- Cargo.lock
- Cargo.toml
- fix: correct parsing of some policy urls
- Tag v1.5.1
This fixes https://github.com/kubewarden/policy-fetcher/issues/131
Once merged, I'll tag a new release
> fix airgap links

- Cargo.lock
- Cargo.toml
> Release 1.6.0-rc5

- Cargo.toml
> Release 1.6.0

- .github/workflows/ci.yml
- .github/workflows/container-image.yml
- .github/workflows/fossa.yml
- .github/workflows/release-drafter.yml
- .github/workflows/release.yml
- .github/workflows/sbom.yml
- .github/workflows/security-audit-cron.yml
- .github/workflows/security-audit-reactive.yml
- .github/workflows/sign-image.yml
Mention all the actions by shasum + their full version.
> chore(deps): be explicit about GH action version

- Cargo.lock
- Cargo.toml
Updates the Cargo.toml file bumping the version to v1.7.0-rc3.
Related to https://github.com/kubewarden/kubewarden-controller/issues/519
> Bump v1.7.0-rc3 version.

- Cargo.lock
- Cargo.toml
Prepare to release next version
> chore: bump version to v1.9.0-rc1

- e2e-tests/test_data/policies.yaml
Update settings of policies used in e2e tests.
> test: update e2e tests policy settings

- Cargo.lock
- Cargo.toml
> build: Bump version to v1.9.0-rc2

- Cargo.lock
- Cargo.toml
build: Bump version to v1.9.0-rc3
CI
> build: Bump version to v1.9.0-rc3

- Cargo.lock
- Cargo.toml
> build: Bump version to v1.9.0

- Cargo.lock
- Cargo.toml
- src/settings.rs
Bumps policy-evaluator to v0.12.2
> build(deps): bump policy-evaluator to v0.12.2

- .github/workflows/release.yml
- kubewarden-dashboard.json
Relates to https://github.com/kubewarden/policy-server/issues/601.
See release:
https://github.com/viccuad/policy-server/releases/tag/v1.9.1-rc1
https://github.com/viccuad/policy-server/actions/runs/7018107156/job/19094518467
> ci: Publish Grafana dashboard as GH release asset

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.9.1 in Cargo.toml

- .github/workflows/sbom.yml
This fixes errors such as "an artifact with this name already exists" after merging https://github.com/kubewarden/policy-server/pull/615.
> ci: Deduplicate sbom artifact upload

- .github/workflows/container-image.yml
> Upgrade artifact upload/download to v4

- .cargo/audit.toml
This security issue doesn't affect us
> cargo audit: ignore RUSTSEC-2023-0071

- Cargo.lock
- Cargo.toml
Starting the path that leads to 1.10 release
> Tag 1.10.0-rc1

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.10.0

- Cargo.lock
- Cargo.toml
> Prepare 1.11.0-rc1 tagging

- Cargo.lock
- Cargo.toml
bump policy-evaluator version to v0.16.2
> build(deps): bump policy-evaluator version to v0.16.2

- Cargo.lock
- Cargo.toml
Updates the version in the Cargo.toml file to v1.11.0-rc3
> chore: bumps version in Cargo.toml to v1.11.0-rc3.

- Cargo.lock
- Cargo.toml
Updates Cargo files bumping the version to v1.11.0-rc5
> chore: bump v1.11.0-rc5.

- Cargo.lock
- Cargo.toml
> Tag 1.11-RC6

- Cargo.lock
- Cargo.toml
Updates Cargo.toml to bump the version to v1.11.0.
> chore: bump v1.11 version.

- Cargo.lock
- Cargo.toml
remove unused dependencies found by using: https://github.com/est31/cargo-udeps
> build(deps): remove unused dependencies

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.12.0-rc2

- tests/common/mod.rs
- tests/integration_test.rs
- Allows using a different PolicyServer config per test
- Adds a verified policy test
> test(integration): clean-up and update integration tests 

- Cargo.lock
- Cargo.toml
> build: Bump version to v1.12.0

- Cargo.lock
- Cargo.toml
Bumps policy evaluator and k8s-openapi to the latest version
> build(deps): bump policy-evaluator version to v0.17.2

- .github/workflows/security-audit-cron.yml
- .github/workflows/security-audit-reactive.yml
This should prevent the action from failing
> test: fix permissions of cargo audit action

- src/lib.rs
Disable readiness probe handler logs, see: https://github.com/tokio-rs/axum/discussions/355
Fixes #775
> fix: disable readiness probe handler logs

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.13.0

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.15.0-rc3

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.15.0

- .github/workflows/openssf.yml
- README.md
- SECURITY_INSIGHTS.yml
Relates to https://github.com/kubewarden/community/issues/12.
CI job will only refresh badge status when it lands on main.
> ci: Add OpenSSF Scorecard workflow and badge 

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.16.0-rc1

- .github/workflows/container-build.yml
Relates to https://github.com/kubewarden/community/issues/12.
Tested here https://github.com/viccuad/policy-server/actions/runs/10371558902.
> ci: Set read permissions for container-build workflow

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.16.0-rc2

- Cargo.lock
- Cargo.toml
CI
Once it lands on main, it will get tagged as `1.16.0`.
> build: Bump version to 1.16.0

- Cargo.lock
- Cargo.toml
Fix breaking change done by Sigstore's TUF repository
> Prepare 1.16.1 release

- Cargo.lock
- Cargo.toml
Prepare for release  v1.17.0-rc2
> chore: prepare to release v1.17.0-rc2

- Cargo.lock
- Cargo.toml
> Prepare 1.17.0-rc3

- Cargo.lock
- Cargo.toml
> build: Bump to 1.17.0-rc4

- Cargo.lock
- Cargo.toml
> Version 1.17.0

- Cargo.lock
- Cargo.toml
chore(deps): bump policy-evaluator
> chore(deps): bump policy-evaluator

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.18.0-beta1

- Cargo.lock
- Cargo.toml
> build: Bump version to v1.18.0-rc1

- Cargo.lock
- Cargo.toml
> Relase 1.18.0

- Cargo.lock
- Cargo.toml
> Prepare for 1.19.0-beta1 release

- Cargo.lock
- Cargo.toml
Use latest version, this is provides latest version of wasmtime
> chore(deps): update policy-evaluator

- Cargo.lock
- Cargo.toml
> prepare 1.19.0 release

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.20.0

- Cargo.lock
- Cargo.toml
Updates policy-evaluator and k8s-openapi.
> chore(deps): updates dependencies.

- Cargo.lock
- Cargo.toml
Updates the jemalloc crates in use. These crates need to be bumped together
> build(deps): bump jemalloc crates.

- Cargo.lock
- Cargo.toml
> prepare for 1.21.0-rc2

- Cargo.lock
- Cargo.toml
> Release 1.21.0

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/metrics.rs
- src/tracing.rs
- tests/data/otel-collector-config.yaml
- tests/integration_test.rs
Updates OTEL libraries and the collector used in the integration tests
> [!WARNING]  
> Keep in mind that the OTEL integration test is flaky and failing before this change. ;)
> chore(build): Update OTEL

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.23.0-beta1

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.23.0-rc1

- Cargo.lock
- Cargo.toml
> build: Bump version to v1.23.0

- src/api/service.rs
…ces and Improve Metrics Handling
Fix #599 
> feat: Skip Wasm Evaluation for Requests from 'Always Allowed' Namespaces and Improve Metrics Handling

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.24.0-rc1

- Cargo.lock
- Cargo.toml
Updates the Cargo files bumping the version to v1.24.0-rc3.
> chore: bump version to v1.24.0-rc3.

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.24.0

- .github/workflows/ci.yml
- .github/workflows/update-rust-toolchain.yaml
- rust-toolchain.toml
- updatecli/DEVELOP.md
- updatecli/updatecli.d/update-rust-toolchain.yaml
- updatecli/values.yaml
Adds the rust-toolchain.toml file to configure the build command on witch toolchain and target it should use.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1093
> chore(deps): add rust-toolchain.toml.

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.25.0-rc1

- src/evaluation/precompiled_policy.rs
> feat: check ```protocol_version``` before storing

- src/evaluation/precompiled_policy.rs
Fix https://github.com/kubewarden/helm-charts/issues/689
CI. Amended relevant test.
> fix: Only check for ProtocolVersion on Wapc execution mode

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.26.0

- Cargo.lock
- Cargo.toml
Updates the policy-evaluator dependency to v0.27.1
> chore: update policy-evaluator.

- Cargo.lock
- Cargo.toml
Updates the policy-evaluator version.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1163
> chore(deps): update policy-evaluator version.

- Cargo.lock
- Cargo.toml
Part of https://github.com/kubewarden/kubewarden-controller/issues/1163
> build: Bump version to 1.27.0-rc1

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.27.0

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.28.0

- Cargo.lock
- Cargo.toml
> build: Bump 1.29.0-rc2

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.29.0-rc3

- Cargo.lock
- Cargo.toml
> build: Bump version to 1.29.0
