kubewarden/policy-server

src/admission_review.rs

Without this change, the JSON-encoded AdmissionReview response object
contains a uid string with escaped double quotes. When used as a webhook
in Kubernetes, the API server will reject a valid pod creation request
with a log message like this:
failed calling webhook "rule-0.chimera.admission.rule": expected response.uid="44286a79-e64e-45f8-b66a-7ef4342e856f", got "\"44286a79-e64e-45f8-b66a-7ef4342e856f\""
This is because the uid is a serde_json::Value object[1]. It needs to be
converted to a &str with as_str and then to a String with to_string() in
order to avoid the extra quotes.
[1] https://docs.serde.rs/serde_json/#operating-on-untyped-json-values

Fix AdmissionReview uid quoted string

---

src/main.rs
src/wasm.rs

Where user input could cause an error, replace calls to unwrap() with
error messages and an exit code rather than panicking.
Fixes #2

Add error handling to main()

---

Cargo.lock
Cargo.toml
src/main.rs
src/wasm_fetcher/https.rs
src/wasm_fetcher/local.rs
src/wasm_fetcher/mod.rs
src/wasm_fetcher/registry.rs

By using a `registry://` schema on the `--wasm-uri` argument, it's
possible to fetch the WASM binary from an artifact enabled OCI
registry.
Fixes https://github.com/chimera-kube/policy-server/issues/1

Implement fetching from an artifact-enabled OCI registry

---

Cargo.lock
Cargo.toml
README.md
policies.yml.example
src/admission_review.rs
src/api.rs
src/main.rs
src/policies.rs
src/utils.rs
src/wasm.rs
src/wasm_fetcher/mod.rs
src/worker.rs

This PR allows policy server to load multiple policies. Each policy has also its own settings, which tune how they behave.
The policies configuration file is a yml file like the following one:
```yaml
valid:
url: file:///home/flavio/hacking/kubernetes/chimera/policy-server/namespace-validate-policy.wasm
settings:
valid_namespace: valid
flavio:
url: file:///home/flavio/hacking/kubernetes/chimera/policy-server/namespace-validate-policy.wasm
settings:
valid_namespace: flavio
empty:
url: file:///home/flavio/hacking/kubernetes/chimera/policy-server/namespace-validate-policy.wasm
settings:
foo: bar
nothing:
url: file:///home/flavio/hacking/kubernetes/chimera/policy-server/namespace-validate-policy.wasm
```
Each policy is identified by a unique ID (`valid`, `flavio`, `empty`, `nothing` in the …

Allow user to define multiple policies

---

src/admission_review.rs
src/api.rs
src/main.rs
src/policies.rs
src/server.rs
src/utils.rs
src/wasm.rs

Significantly reduce the usage of `unwrap`, each invocation now should not cause a panic to happen.

Improve code quality

---

src/main.rs
src/wasm_fetcher/https.rs
src/wasm_fetcher/mod.rs
src/wasm_fetcher/registry.rs

Prior to this commit the policies would be downloaded into the local execution  directory. This commit allows the user to specify where the policies files downloaded from a HTTP(s) server/OCI registry should be saved.
This is needed to run policy-server containerized. Without this patch the server would try to download the policies to `/usr/local/bin`, which is a bad thing; plus it's not writable by the unprivileged user running inside of the container.

Allow user to choose where to download policies

---

sources.yml.example
src/main.rs
src/registry/config.rs
src/sources.rs
src/wasm_fetcher/fetcher.rs
src/wasm_fetcher/https.rs
src/wasm_fetcher/local.rs
src/wasm_fetcher/mod.rs
src/wasm_fetcher/registry.rs

Implements https://github.com/chimera-kube/policy-server/issues/23
Now it is possible to provide a `sources.yaml` file that will inform
`policy-server` how to treat certain hosts, both for
HTTPs (`https://`) and oci-registry (`registry://`) origins.
The behavior of the implementation is very similar to Docker's
insecure registries.
The content of the sources.yaml file is of the form:
```yaml
insecure_sources: ["company-a.com", "company-b.com"]
source_authorities:
company-c.com:
ca_path: "/some/path/to/company-c-ca-chain.crt"
company-d.com:
ca_path: "/some/path/to/company-c-ca-chain.crt"
```
Behavior for `https://` scheme is as follows:
1. If CA's provided in source authorities, download with provided CA's
2. If no source authorities provided, download with system CA's
2.1. If it fails and …

Implement sources for Wasm modules origin

---

.github/workflows/testdrive-release.yml

Build the policy-testdrive binary in a staic way and add the final artifact to the release page

GitHub action: release static binary of policy-testdrive

---

Cargo.lock
Cargo.toml
crates/policy-evaluator/Cargo.toml
crates/policy-evaluator/src/policy_evaluator.rs
src/api.rs
src/main.rs
src/server.rs
src/worker.rs
src/worker_pool.rs

Use the tokio/tracing crate to implement tracing.
The policy-server is now honoring its `--debug` flag (previously the value of this flag wasn't handled).
Moreover a new flag `--log-fmt` has been introduced. This allows to choose between two types of log format:
* `text`: simple text
* `json`: json output
Regardless of the output format, all the events are structured logs.
Fixes https://github.com/chimera-kube/policy-server/issues/3

Implement proper logging

---

Cargo.lock
Cargo.toml
crates/policy-evaluator/Cargo.toml
crates/policy-testdrive/Cargo.toml

Just use the crate we published on crates.io, instead of using a random commit from git

Use the Kubewarden SDK crate we just published

---

.github/workflows/testdrive-release.yml

The uncompressed file is 22Mb, the compressed one is ~8Mb

Compress the policy-testdrive binary

---

crates/policy-evaluator/src/policy_evaluator.rs

Unfortunately waPC doesn't provide a specific error message when the host tries to call a non-existent function.
Parsing the error message returned by the waPC host library is highly unreliable: it turns out the error string is generated by the waPC guest SDK. That means each language, and each version of the language SDK, can generate a completely different error message.
This commit enforces all the policies to provide a `validate_settings` callback.

Always fail when a policy doesn't provide `validate_settings`

---

crates/policy-evaluator/src/cluster_context.rs

Whenever the `policy-server` or the `policy-testdrive` binaries try to
initialize a Kubernetes threaded update loop and fail, a panic message
was printed in the standard error.
Print a less critical message, and show a regular warning instead.
Fixes https://github.com/kubewarden/policy-server/issues/50

Fix threaded panic when a Kubernetes client cannot be built

---

Cargo.lock
Cargo.toml
crates/policy-evaluator/Cargo.toml
crates/policy-evaluator/src/validation_response.rs

This is needed to support policies written with v0.2.0 of the SDK
Once this is merged I'll tag a new release of policy-server

Update to latest version of kubewarden's client SDK

---

.github/workflows/testdrive-release.yml

Fix the release action of policy-testdrive by ensuring the linux binary is properly compressed.
This fixes issue #47

Fix the release pipeline of `policy-testdrive`

---

Cargo.lock
Cargo.toml

Use the latest version of policy-fetcher. That, as a result, will bring in an edge release of oci-distribution.
The oci-distribution crate has been upgraded to the latest tokio release, making the dependency of tokio-compat obsolete

Update the policy-fetcher dependency

---

Cargo.lock
Cargo.toml

Update to latest version of policy-evaluator, this will use the latest stable release of wasmtime-provider, which will then use the latest version of wasmtime. :turtle: over :turtle: over :turtle: 
This is needed to solve a wasmtime security issue.

[fix] Address wasmtime security issue

---

CONTRIBUTING.md

Adapt CONTRIBUTING.md contents explaining how to include certain changes in the changelog generator.

Update CONTRIBUTING.md to add commit subject information

---

src/worker.rs

Fixes: https://github.com/kubewarden/policy-server/issues/76
When reading the policy and constructing a policy evaluator for it,
read the runtime annotation on the policy metadata and honor it. If
this annotation is present, fallback to the default settings of the
runtime: currently the Kubewarden Wapc backend.

opa: read policy execution mode when setting up the policy evaluator

---

otel-collector-minimal-config.yaml
src/cli.rs

This PR fixes the integration with opentelemetry otlp collector. When we updated the project dependencies we introduced 2 regressions:
1. The name of the service was not propagated by the otlp collector to other endpoints/collector
2. opentelemetry was not sending traces in batch mode. This is the recommended way for production deployments, otherwise the performance of the whole application will be affected by trace propagation
Finally, the PR adds a sample configuration file of otlp collector receiving events from policy-server and then sending them to a jaeger endpoint

Fix opentelemetry otlp integration

---

Cargo.lock
Cargo.toml
src/worker.rs
src/worker_pool.rs

Fixes:https://github.com/kubewarden/policy-server/issues/86
If any Rego policy refers to an unimplemented builtin, abort the execution of the whole policy-server.

Abort execution if any policy has missing Rego builtins

---

src/api.rs
src/cli.rs
src/worker.rs

Improve the tracing experience: add the hostname of the machine (or Pod) as part of the tags. This makes possible to find all the trace events generated by a certain deployment of policy-server.
Also, remove some unwanted debug statements from the stdout.

Tracing improvements

---

Cargo.lock
Cargo.toml
src/main.rs

Fixes: https://github.com/kubewarden/policy-server/issues/88
The reported information includes:
- The name that was given to the policy in the configuration
- The SHA-256 sum of the policy itself
- Whether the policy is mutating or not

feat: report loaded policies on startup

---

Cargo.lock
Cargo.toml

A newer version of base64ct (1.2.x) is bumped to Rust Edition
2021. Keep a pinned version to 1.1.1 of base64ct that did depend on
Rust Edition 2018.
We can get rid of this when we are ready to move to Edition 2021.

chore: pin base64ct to 1.1.1 version for Rust Edition 2018

---

.cargo/audit.toml

By adding a cargo audit configuration we are able to ignore security
advisories that don't apply.
Related: https://github.com/kubewarden/policy-server/issues/110

chore: add cargo audit configuration

---

kubewarden-dashboard.json

During a past demo, I ended up performing some improvements in our Grafana Dashboard to enhance the data visualization. 
The Grafana Dashboard has been updated enforcing a color standard. Now all the graphics related to mutated request are purple, accepted requests are green, reject requests are red.
Furthermore, some queries have been updated to aggregate different time series in one single line.  This is necessary because we have many label in the metrics and each different value generate another time series. Thus, we can leave with many lines in the graph which does not tell use useful info.

Dashboard color standards and better aggregations.

---

Cargo.toml
README.md
src/cli.rs
src/main.rs
src/settings.rs
verification.yml.example

- Add `--enable-verification`, `--verification-path` flags and their corresponding env vars `KUBEWARDEN_ENABLE_VERIFICATION`, `KUBEWARDEN_VERIFICATION_CONFIG_PATH`.
- If `--enable-verification` or `KUBEWARDEN_ENABLE_VERIFICATION` is set, read the verification yaml file (default `verification.yml`). the policy-server will verify the policy using all the keys provided and all the annotations. Expecting verification and providing no verification keys is regarded an error. Verification annotations are optional. Emit logs with `status=verified-signatures`, `status=verified-local-checksum`.
Examples:
With policies.yml:
```yaml
pod-privileged:
url: registry://ghcr.io/kubewarden/tests/pod-privileged:v0.1.9
```
1. And verification.yml:
```yaml
---
verification_keys:
key-name-irrelevant: | …
```

feat: Sigstore verification of policies on download

---

Cargo.lock
Cargo.toml
src/main.rs
src/worker.rs
src/worker_pool.rs

Ensure policies can invoke asynchronous code on the host. This is implemented by using the new CallbackHandler provided by policy-evaluator.
This allows the usage of the waPC host call that fetches the digest of a container image

Integrate the CallbackHandler

---

Cargo.lock
Cargo.toml

Update the policy-evaluator crate to ensure openssl-sys is not pulled in.
This fixes container image building.

Fix container image build

---

src/cli.rs

`matches.is_present("verification-path")` is always true, as the flag has `.default("verification.yml")`. Remove default.
Tested locally with `cargo run --release -- --policies policies.yml --workers 2 --log-fmt otlp --log-level debug`, and the `--verification-path` flag.
Fixes https://github.com/kubewarden/policy-server/issues/98

fix: Don't default to verification always enabled

---

.cargo/config
.github/workflows/container-image.yml
.gitignore
Dockerfile

Create multi-arch container images by first cross compiling the
binaries for the different platforms, and then creating the container
images by copying the binaries.

cross-compile container images

---

.github/workflows/release.yml

This action creates a pre-release GitHub release if the tag contains
'-alpha', '-beta' or '-rc'.
Fixes: https://github.com/kubewarden/policy-server/issues/143

Create GitHub release when a tag is pushed

---

Makefile
src/settings.rs
src/worker.rs

Adds the "mutating" field in the settings. This allows policy server to check if a policy is allowed to mutate a request. If the policy mutate the request, but its "mutating" settings is false, the request is rejected.
Fixes: https://github.com/kubewarden/policy-server/issues/137.

 Adds mutating settings field.

---

Cargo.lock
Cargo.toml
src/cli.rs
src/main.rs

Adapt the code to address the major changes brought by the major update of clap.
Also, dropped the custom code we had to write to handle `--enable-XXX` flags via environment variables. Clap v2 didn't support them, but this got addressed with v3.
Now it's possible to enable verification and monitoring via `KUBEWARDEN_ENABLE_METRICS=1` and `KUBEWARDEN_ENABLE_VERIFICATION=1` without our custom code.
This supersedes https://github.com/kubewarden/policy-server/pull/148

Update to latest version of clap

---

src/main.rs

This was dropped in the clap bump.
With this, the correct behaviour is back:
- use verification if `--enable-verification` or `KUBEWARDEN_ENABLE_VERIFICATION=1` is present.
-  use verification if `--verification-path=foo` is present (expected by controller).

fix: Enable verification if `--verification-path` is passed

---

src/settings.rs
src/utils.rs
src/worker.rs

Do not flatten the `settings` field that would behave as a "catch-all"
for unknown attributes.
This would silently make the `policy-server` forward certain
attributes to policies when keys change on the configuration. We
should plan for such changes and have a migration path.
Policies should only receive as `settings` what is intended as such.

Do not flatten settings

---

Cargo.lock
Cargo.toml
src/metrics/mod.rs
src/settings.rs
src/worker.rs

Fixes: https://github.com/kubewarden/policy-server/issues/190
feat: implement policy modes
Policies can be configured to either be in `monitor` or `protect`
modes. When a policy is in `protect` mode, it will accept, reject or
mutate requests. When a policy is in `monitor` mode, it will always
accept all requests, but will log what would have been its decision if
it had been in `protect` mode.
This is helpful if you want to check how a policy would behave before
it starts to take decisions on a Kubernetes cluster.

Monitor mode

---

src/api.rs

add info to traces about why a resource was rejected by a policy
Fix #206

feat: add info to traces about why a resource was rejected by a policy

---

Cargo.lock
Cargo.toml

The kube crate version v0.70.0 added support for ECDSA algorithm. Which is necessary to fix a certificate issue when trying to run PolicyServer in K3D and Minikube cluster. This commit updates the crate version to fix the issue.
Fix #136 
Depends on https://github.com/kubewarden/policy-evaluator/pull/114
```shell
cargo run --release -- --policies policies.yml --workers 2
```

Update kube crate to version v0.71.0 and policy-evaluator to v0.2.18.

---

Cargo.lock
Cargo.toml
src/main.rs

pass fulcio_and_rekor_data to the Callback handler builder, since it is now needed for running policies that uses sigstore verification
Fix https://github.com/kubewarden/policy-server/issues/99

feat: Allow policy authors to write policies that perform image verification using sigstore

---

Cargo.lock
Cargo.toml

This is a leftover from an old Sigstore-related iteration.
The dependency is no longer needed.

Remove the rust Policy SDK dependency

---

src/cli.rs
src/main.rs
src/worker.rs
src/worker_pool.rs

Fixes: https://github.com/kubewarden/policy-server/issues/246
Add an `--always-accept-admission-reviews-on-namespace` option that
will always allow requests on the given namespace. Mutations are not
altered, and are allowed to happen in this namespace. However, all
evaluations of all policies will be evaluated to `allowed: true` if
provided.
This argument is optional, and by default, if not provided, the
behavior of the `policy-server` is unchanged.
This argument can also be provided as an environment variable named
`ALWAYS_ACCEPT_ADMISSION_REVIEWS_ON_NAMESPACE`.
This argument only accepts one namespace, either provided as a CLI
argument or as an environment variable. Providing a list of namespaces
is not supported.

Add option to always accept admission reviews on a given namespace

---

Cargo.lock
Cargo.toml

Support policies performing revers DNS lookups
Update to latest version of policy-evaluator, so that new waPC functions are supported.
This is needed to fix https://github.com/kubewarden/policy-server/issues/236
Note well: this builds on top of https://github.com/kubewarden/policy-server/pull/242

support wapc dns lookup

---

.github/workflows/container-image.yml

Use cosign keyless to sign the policy-server image
Tested in my [fork](https://github.com/raulcabello/policy-server/runs/6503089885?check_suite_focus=true) 
```
COSIGN_EXPERIMENTAL=1 cosign verify ghcr.io/raulcabello/policy-server:latest | jq
```
output:
```
...
"Issuer": "https://token.actions.githubusercontent.com",
"Subject": "https://github.com/raulcabello/policy-server/.github/workflows/container-image.yml@refs/heads/main"
...
```
Fix #255

Sign policy-server image

---

Cargo.lock
Cargo.toml
src/kube_poller.rs
src/main.rs

* Update to latest version of policy-evaluator
* Remove the kube dependency, this is now exported by policy-evaluator
* Update to latest version of k8s-openapi

Update a bunch of dependencies

---

Cargo.lock
Cargo.toml
src/admission_review.rs
src/api.rs
src/communication.rs
src/main.rs
src/server.rs
src/worker.rs

Prior to this commit, we used the low level hyper to create our HTTP server. The code being used was pretty complex due to the low level nature of this library.
Moreover, the code wasn't robus enough. In certain cases the HTTP server could fail and cause the whole policy-server to drop incoming requests.
This kind of failures was hard to reproduce, but some users have run into that.
I was able to reproduce that too with minikube. Malformed client TLS requests could cause the server to reject them and then enter an error state.
Instead of implementing all the possible workarounds for these kind of situations, this code now implements the HTTP and HTTPS server using the warp crate.
Warp is built on top of hyper, but provides a ready to be consumed high level API.
Our core business is not …

cleanup http server

---

Cargo.lock
Cargo.toml

- chore(deps): lock file maintenance (from https://github.com/kubewarden/policy-server/pull/281)
- Update to latest version of policy-evaluator to fix the compilation errors

update to latest policy evaluator

---

Cargo.toml
src/cli.rs

Allow user to have the default `text` log produce entries that are not colored.
This can be done in two ways:
* Via the `--log-no-color` flag
* By setting the following environment variable: `KUBEWARDEN_LOG_NO_COLOR=1`

[feat] allow text logs to not have color

---

CHANGELOG.md
Cargo.toml

run `TAG=v1.1.0 make tag` Bump to v1.1.0, update changelog.
I don't have perms to push commits directly to main, but I have perms to push the tag.
Which means that the tag is pointing to https://github.com/kubewarden/policy-server/commit/5cec93f8096ceeb21975b3917018fb33e22dc645 even if it hasn't landed in main.
I have cancelled the GHA workflows. They could be retriggered again.
Either merge this, or delete tag, run `TAG=v1.1.0 make tag`, and push everything to main.

Road to 1.1.0

---

src/metrics/mod.rs
src/worker.rs

Updates the worker code used to run the policy evaluation to use the vanilla admission response from the policy in the metrics. Thus, the users will be able to actually see what policies are doing before the values updates in monitor and protect modes.
Remove the `resource_name` from the prometheus metrics to avoid too much time series, reducing the data stored and simplifying the query used to extract information from the metrics. This is a best practice:  https://prometheus.io/docs/practices/naming/
Fixes #263

Prometheus metrics fixes 

---

.github/workflows/container-image.yml

In the prevision commit the dependency between job in the CI workflow has been disabled for testing purposes. The PR got merged without restoring the previous configuration. This commit fix that.

Reconfigure CI jobs dependencies.

---

.github/workflows/container-image.yml
.github/workflows/release.yml
.gitignore
Cargo.toml
Makefile
README.md

Adds new steps in the build and release workflow to generate, sign and publish a SBOM file for Policy Server.
Fix #305

SBOM file generation.

---

README.md

Relates to https://github.com/kubewarden/kubewarden.io/issues/120.
Should satisfy https://clomonitor.io/docs/topics/checks/#security-policy.

docs: Add security link

---

.github/workflows/container-image.yml

Ensure the SBOM for the tagged container image (like `policy-server:2.0.0`) is created.
Prior to this commit, the creation of the SBOM failed because the signing action was trying to obain the digest of the `latest` container image.
This fixes build errors like this one: https://github.com/kubewarden/policy-server/actions/runs/3298307317/jobs/5440643528

fix: create SBOM for tagged container image

---

.github/workflows/container-image.yml

Sometimes ago we upgraded the `actions/download-artifact` action to a major tag (v1 -> v2), this changes the behaviour used when extracting the artifacts.
That causes the container image to have `/policy-server/policy-server-x86_64` instead of `/policy-server`

fix: ensure container image has the binary

---

.github/dependabot.yml

A lot of our GH actions were not updated by renovatebot, dunno why.
Asking dependabot to look after them

chore: tell dependabot to look after github actions

---

.github/workflows/container-image.yml

Add the signagures of the `policy-server` binaries to the same zip file. Previously, they where put into a dedicated zip file.
This change is needed to make CLOMonitor that we are signing all our assets.

fix: add binaries signatures to the same zip file

---

README.md

Adds Artifacthub badge pointing to the kubewarden-defaults Helm chart

Artifacthub and OpenSSF badges

---

.github/workflows/container-image.yml
.github/workflows/fossa.yml
.github/workflows/release.yml
.github/workflows/security-audit-cron.yml
.github/workflows/security-audit-reactive.yml
.github/workflows/tests.yml

Setting token permissions to read-only follows the principle of least privilege. This is important because attackers may use a compromised token with write access to push malicious code into the project. [More info](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions)
This will increase our CLOMonitor score
Fix #359

Add read-all permission to all workflows

---

Cargo.lock
Cargo.toml

Update to latest version of policy-evaluator to support the new certificate based verification host capability.
Fixes https://github.com/kubewarden/policy-server/issues/366

feat: support certificate based verification

---

src/server.rs

Remove the warnings produced by warp and the latest rust 1.66 release.
The fix is taken from https://github.com/seanmonstar/warp/issues/1012

chore: address clippy warnings caused by warp and rust 1.66

---

.github/workflows/tests.yml
Cargo.lock
Cargo.toml
Makefile
e2e-tests/.gitignore
e2e-tests/01-setup.yml
e2e-tests/02-monitor-and-protect-modes.yml
e2e-tests/03-audit-endpoint.yml
e2e-tests/04-timeout-protection.yml
e2e-tests/99-teardown.yml
e2e-tests/Makefile
e2e-tests/e2e-tests-policies/.gitignore
e2e-tests/test_data/pod_sleep_100ms.json
e2e-tests/test_data/pod_sleep_4s.json
e2e-tests/test_data/pod_with_privileged_containers.json
e2e-tests/test_data/policies.yaml
src/cli.rs
src/main.rs
src/worker.rs
src/worker_pool.rs

Ensure a policy cannot run more than a given amount of time.
This is required to fix https://github.com/kubewarden/policy-server/issues/254
Note 1: this PR builds on top of https://github.com/kubewarden/policy-server/pull/388 to ensure all the tests are passing
Note 2: this PR depends on https://github.com/kubewarden/policy-evaluator/pull/224

feat: policy timeout protection

---

.github/workflows/release.yml

Updates the release CI job to trigger an event to the Helm chart repository to ensure that the major and minor releases will be in sync between all Kubewarden components.
Fix https://github.com/kubewarden/policy-server/issues/376

Trigger Helm chart release.

---

.github/release-drafter.yml

Updates the release drafter configuration file changing the label used to exclude a PR from the change log to `release/skip-changelog`.
Adds a new entry in the autolabel configuration to set the label `area/dependencies` when the PR title starts with `build(deps)`

Fix release drafter autolabeler and exclude-labels.

---

.cargo/audit.toml

Cargo audit is now failing because of [RUSTSEC-2021-0146](https://rustsec.org/advisories/RUSTSEC-2021-0146).
This is about `twoway` not being maintained anymore. This is a transitive dependency of `multipart`, which is a dependency of `warp`.
[This is the GH issue](https://rustsec.org/advisories/RUSTSEC-2021-0146) that describes the problem.
There's nothing we can do in the meantime. We have to ignore this warning otherwise it will not be possible to merge PRs.

chore: ignore twoway warning

---

src/cli.rs
src/main.rs
src/policy_downloader.rs
src/worker.rs
src/worker_pool.rs

Get rid of clippy warnings generated by the latest version of rust

chore: fix clippy warnings

---

Cargo.lock
Cargo.toml
e2e-tests/05-rego-policy.yml
e2e-tests/test_data/policies.yaml
e2e-tests/test_data/service-clusterip.json
e2e-tests/test_data/service_loadbalancer.json

Ensure Rego policies are being tested as part of the e2e tests.
This would have allowed us to spot https://github.com/kubewarden/policy-server/issues/413 immediately.
**WARNING:** the e2e tests inside of this PR will keep failing until the fix for https://github.com/kubewarden/policy-server/issues/413 lands into this branch. That's a feature! :smile:

test: extend e2e tests

---

.github/workflows/container-image.yml

Cosign 2.0 was [released last week](https://blog.sigstore.dev/cosign-2-0-released/) (yay!) but, as expected because semver, it's not backwards compatible (nay!).
Pin cosign-installer GHA so it downloads cosign 1.*.
Latest [cosign-installer downloads cosign 2.*](https://github.com/sigstore/cosign-installer/releases/tag/v3.0.0).
Tested in other repos.

deps: Pin cosign to 1.* by pinning cosign-installer GHA

---

.cargo/audit.toml

cargo-audit is complaining because the `mach` dependency is currently not maintained.
This is a transitive dependency of wasmtime.
The issue is tracked upstream via https://github.com/bytecodealliance/wasmtime/issues/6000
In the meantime we will silence this warning.

chore: fix cargo audit

---

.cargo/audit.toml
Cargo.lock
Cargo.toml

Update warp to the latest release. This removes the multipart dependency, which was no longer maintained

chore(deps): update warp

---

Cargo.lock
Cargo.toml
src/worker_pool.rs

Adds a function to check if the policy is running in a policy server with the minimum Kubewarden version required.
Fix #440
This PR depends on this [PR](https://github.com/kubewarden/policy-evaluator/pull/268) from policy-evaluator

Check minimum Kubewarden version.

---

Cargo.lock
Cargo.toml
e2e-tests/.gitignore
e2e-tests/01-setup.yml
e2e-tests/06-wasi-policy.yml
e2e-tests/test_data/pod_creation_flux_cat.json
e2e-tests/test_data/policies.yaml

Support policies that implement the new WASI protocol.
This policy execution mode is not the best one, but it allows the execution of WASM modules that do not leverage waPC. This is the case of modules built by the official Go compile.

wasi policies

---

.github/release-drafter.yml

Updates the release drafter configuration file to properly label renovate bot PR starting with "fix(deps)" as area/dependencies. Therefore, the PR will land in the "Maintenance" change log section.

fix: properly auto label dependencies fixes.

---

.github/workflows/release.yml

Updates the release CI to publish the draft release created by release drafter instead of creating a new release. Therefore, we will use the nice changelog.
Fix #435

fix: publish release drafter draft release.

---

.github/release-drafter.yml

Updates the release drafter configuration file to show PR tagged with kind/feature in the feature section in the changelog.

fix: missing label in the changelog feature section.

---

.github/workflows/release.yml

The release CI script is not building the payload used to update the Helm charts properly. It is not setting the right new version in the payload. This commit fixes that by using the github context to get the proper tag name to build the payload.

fix: release CI doesn't fetch the right new version.

---

.github/workflows/container-image.yml

Updates the CI scripts updating the cosign-installer to v3. Thus, the cosign version now is v2. Which has breaking changes requiring some changes on how the command is called and removing the need of using environment variable to enable keyless signature.
Related to https://github.com/kubewarden/kubewarden-controller/issues/411

Updates cosign to v2.

---

Cargo.lock
Cargo.toml
src/main.rs
src/worker_pool.rs

Reduce the amount of memory being used by policy-server at runtime.
This table contains a comparison of the memory usage (Mb) before and after this optimization:
| Workers (#) | Vanilla (Mb) | Optimized (Mb) | Improvement (%) |
|-------------|--------------|----------------|-----------------|
| 1           | 634.356      | 506.484        | -20.16          |
| 2           | 790.672      | 598.902        | -24.25          |
| 3           | 954.726      | 680.124        | -28.76          |
| 4           | 1108.042     | 774.498        | -30.10          |

fix(perf): reduce memory usage

---

Cargo.lock
Cargo.toml
DEVELOPMENT.md
policies.yml.example
src/metrics/mod.rs
src/metrics/policy_evaluations_latency.rs

Update opentelemetry dependencies and adapt existing code to the new API.
Dependencies updated:
[TODO] insert list here
Resolves: #493 
-

build(deps): update opentelemetry

---

.gitignore
hack/docker-compose.yml
hack/otel-collector-minimal-config.yml

Bumps opentelemetry collector dev container to 0.85.0, and switches to OTLP exporter for Jaeger.
following the DEVELOPMENT.md guide is working (aka metrics and traces are collected correctly)
Related to: https://github.com/kubewarden/helm-charts/pull/317

chore: bump otel collector dev container to 0.85.0

---

Cargo.lock
Cargo.toml
e2e-tests/07-raw-policies.yml
e2e-tests/test_data/policies.yaml
e2e-tests/test_data/raw_mutation.json
e2e-tests/test_data/raw_validation.json
src/admission_review.rs
src/api/audit_and_validation.rs
src/api/mod.rs
src/communication.rs
src/main.rs
src/metrics/mod.rs
src/metrics/policy_evaluations_latency.rs
src/metrics/policy_evaluations_total.rs
src/policy_downloader.rs
src/raw_review.rs
src/server.rs
src/settings.rs
src/worker.rs
src/worker_pool.rs

This PR implements: https://github.com/kubewarden/kubewarden-controller/issues/527
TODO: 
A new API endpoint `validate_raw` is added, which deals with raw policy requests:
Request
```json
{
"request": {
"uid": "123",
"user": "tonio",
"action": "eats",
"resource": "banana"
}
}
```
Response
```json
{
"response": {
"uid": "123",
"allowed": true,
"auditAnnotations": null,
"warnings": null
}
}
```
When writing a policy the user Is expected to parse the payload wrapped such as:
```
{
"request": <payload> 
}
```
It also creates a new type of response for RawRequests which does not have any k8s related field (apiversion, kind, etc...).
Metrics have been refactored to support Raw policies.
-

feat: raw policy validation

---

src/policy_downloader.rs

Use a `tokio::sync::Mutex` inside of an async context. This prevents the tokio runtime from blocking.
This will avoid slowdowns of the async routines.
I detected that with a linter.

fix: use async Mutext

---

src/communication.rs
src/metrics/mod.rs
src/worker.rs

Relates to https://github.com/kubewarden/policy-server/issues/597
This new `request_origin` field informs if the policy request was a `validate` one (going through the k8s apiserver) or an `audit` one (synthetic evaluation requests generated by the audit scanner).
Tested successfully with `docker compose`, by adding a new grafana visualization such as
`sum(kubewarden_policy_evaluations_total{request_origin="validate"})`.

feat: Add new `request_origin` to metrics baggage

---

kubewarden-dashboard.json

Relates to https://github.com/kubewarden/policy-server/issues/597
- Bump dashboard to schemaVersion 38, from Grafana vesion 10.2.0.
- Filter the preexisting visualizations with `request_origin="validate"`.
- Add new visualizations pertaining audit requests, filtering with `request_origin="audit"`.
- Leave latency, pod visualizations untouched.
Tested by deploying grafana with docker compose, and editing the dashboard via the UI. The UI has a linter and informs if the queries fail to parse or are invalid.
Still would be good to test it against an audit scanner + opentelemetry deployment.

feat: Expand grafana dashboard, bump to schemaVersion 38

---

Cargo.lock
Cargo.toml
e2e-tests/test_data/policies.yaml
src/config.rs
src/lib.rs
src/workers/error.rs
src/workers/evaluation_environment.rs
src/workers/mod.rs
src/workers/policy_evaluation_settings.rs
src/workers/pool.rs
src/workers/precompiled_policy.rs
src/workers/worker.rs

Reduce the memory consumption of Policy Server when multiple instances of the same Wasm module are loaded.
Thanks to this change, a worker will have only once instance of `PolicyEvaluator` (hence of wasmtime stack), per unique type of module.
Literally speaking, if a user has the `apparmor` policy deployed 5 times (different names, settings,...) only one instance of `PolicyEvaluator` will be allocated for it.
Warning: the optimization works at the worker level. Meaning that `PolicyEvaluator` are NOT sharing these instances between themselves.
This commit helps to address issue https://github.com/kubewarden/kubewarden-controller/issues/528
Note 1: this depends on https://github.com/kubewarden/policy-evaluator/pull/390
I've collected data about the amount of memory consumed by 1 instance of …

refactor: reduce memory usage

---

.github/workflows/release.yml
.github/workflows/sbom.yml

{upload,download}-artifact v4 don't accept uploading the same named artifact. Suffix their names with the arch, and download all of them at once into the same dir, as it was before.
Relates to https://github.com/kubewarden/policy-server/pull/616.
Tested on my fork: https://github.com/viccuad/policy-server/actions/runs/7260109787
Release workflow change untested, it's the same as in https://github.com/kubewarden/audit-scanner/pull/162, so refer to that one.

ci: Fix artifact upload and download

---

Cargo.lock
Cargo.toml
src/policy_downloader.rs

Updates the Cargo files pointing to the policy-evaluator version with the new capability to allow users to fetch OCI image manifest.
Fix #653

feat: update policy-evaluator enabling OCI image capability.

---

.github/workflows/ci.yml
.gitignore
Makefile
coverage/integration-tests/.gitignore
coverage/unit-tests/.gitignore

Fix https://github.com/kubewarden/policy-server/issues/661
Add new make targets `coverage, `coverage-unit-tests`, `coverage-integration-tests` that are used in the CI. They run the tests via `cargo-tarpaulin` with llvm, and save the reports to the respective new folders `coverage/{unit-tests,integration-tests}/*`.
The make targets are both configured with `cargo +nightly`, as `cargo-tarpaulin` for the integration-tests need it, and in this way we can skip recompiling again. 
Add new CI job that runs the tests via the new makefile targets and uploads the result to codecov.
CI, PR should get a "welcome to codecov" message, and audit-scanner appear under https://app.codecov.io/github/kubewarden/.

ci: Add codecov support

---

.github/workflows/ci.yml
Makefile

Relates to https://github.com/kubewarden/policy-server/pull/667
No need.

chore: Remove tarpaulin comment, reword job

---

Cargo.lock
Cargo.toml

Change the way Kubernetes resources are fetched by context aware policies.
Use what Kubernetes calls: "the informer pattern".
Fixes https://github.com/kubewarden/kubewarden-controller/issues/575

feat: use informer pattern to fetch k8s resources

---

Cargo.toml

Prepare for `v1.11.0-rc2` release

chore: bump version to v1.11.0-rc2

---

Cargo.lock
Cargo.toml
src/api/handlers.rs
src/cli.rs
src/config.rs
src/lib.rs
src/profiling.rs
tests/common/mod.rs

Allow CPU profiling using pprof. There's a new boolean flag `--enable-pprof` that exposes a new HTTP endpoint named `/debug/pprof/cpu`.
By doing a GET request against the endpoint, a pprof profile is generated and downloaded.
The endpoint takes two optional query parameters:
- interval: the length in seconds of the profile (30 secs by default)
- frequency: profiling frequency (99 Hz by default)
While working on this feature, I found some issues related with cli flags:
- fix: show cli options sorted
- fix: improve handling of boolan flags
- test: test parsing of boolean flags

add pprof support

---

.github/workflows/ci.yml

Updates the ci.yaml workflow file to use the new github action created to install the cargo tarpaulin.
Related to https://github.com/kubewarden/kubewarden-controller/issues/667

chore: use tarpaulin-install action to install tarpaulin.

---

src/api/service.rs
src/evaluation/errors.rs
src/evaluation/evaluation_environment.rs
src/evaluation/precompiled_policy.rs
src/lib.rs
src/policy_downloader.rs
tests/common/mod.rs
tests/integration_test.rs

Fix: #682
The policy server was exiting with an error If a policy could not be downloaded, verified, or had invalid settings, causing the Pod to restart. The policy server pod entered a crash back-off loop in the worst-case scenario. 
This PR changes the way the policy server manages policy initialization errors by not exiting and storing the error in the evaluation environment so it can be bubbled up to the API in the form of a rejected `AdmissionResponse` with the error as message and the status code set to `500`.

feat: do not exit on policy error

---

src/api/service.rs
src/metrics.rs

Adds policy initialization error metric

feat: add policy initialization error metric

---

Cargo.lock
Cargo.toml
src/lib.rs
src/policy_downloader.rs

The Sigstore project changed the internals of its TUF repository, which broke sigstore-rs.
This commit updates to the latest version of sigstore-rs. The code changes have been caused by the massive changes done by sigstore-rs.
Fixes https://github.com/kubewarden/kwctl/issues/753

fix: address changes done to Sigstore TUF repository

---

src/cli.rs
src/config.rs
src/evaluation/evaluation_environment.rs
src/lib.rs
tests/common/mod.rs

Adds a flag to toggle the "continue on errors" behavior, so we can keep working on the policy server error handling flow without breaking the current user experience.
Fixes: #730

fix: add hidden flag/env to toggle continuing on initialization errors

---

src/lib.rs
src/policy_downloader.rs

Fixes #736 
`PolicyDownloader` was refactored so that we initialize the `ManualTrustRoot` just once and pass it to the constructor.

fix: sigstore cache dir error

---

Cargo.lock
Cargo.toml
src/main.rs

Switch to jemalloc, fixes #763.
The allocator is configured to prioritize memory usage, see: https://github.com/jemalloc/jemalloc/blob/dev/TUNING.md
Also, the  `unprefixed_malloc_on_supported_platforms` feature was enabled, see https://github.com/tikv/jemallocator/blob/master/jemalloc-sys/README.md#features

feat: switch to jemalloc allocator

---

.github/workflows/security-audit-cron.yml
.github/workflows/security-audit-reactive.yml

Move to the official GH action provided by the cargo-audit team. The old one seems abandoned.

chore(deps): change GH action used by cargo-audit

---

src/lib.rs
src/main.rs
tests/common/mod.rs

Integration tests were failing since we were activating the profiling, but there jemalloc was not configured in `lib.rs` (integration tests instantiate a policy server using the library part of the crate).
Also, we don't need to enable pprof when testing, since it could slow down the CI.

fix: configure jemalloc in lib.rs

---

Dockerfile
src/lib.rs

Ensure sigstore Trust Root is always fetched. We must always fetch the Sigstore Trust Root, otherwise policies making use of Sigstore won't be able to do keyless verifications.
Prior to this commit, the Trust Root was fetched only when the policy integrity verification was turned on.

sigstore fixes

---

Cargo.lock
Cargo.toml

build: Bump version to 1.13.1

---

Cargo.lock
Cargo.toml

Bumps the policy-server version in the Cargo files to v1.14.0-rc1. It also updates the policy-evaluator version.

chore: bump version to v1.14.0-rc1.

---

Cargo.lock
Cargo.toml

Bumps the policy-server version in the Cargo files to v1.14.0-rc2.

chore: bump version to v1.14.0-rc2

---

Cargo.lock
Cargo.toml

Bumps the policy-server version in the Cargo files to v1.14.0.

chore: bump version to v1.14.0

---

Cargo.lock
Cargo.toml
hack/docker-compose.yml

- CI.
- Performing docker-compose local deployment and testing: Tracing is broken, as jaeger fails to connect with otel-collector. This is because we aren't pinning jaeger.
- end-to-end tests: broken for latest jaeger-operator-2.54.0. Working for jaeger-operator-2.49.0, the one we list as supported in https://docs.kubewarden.io/reference/dependency-matrix.

deps: Bump opentelemetry dependencies

---

policies.yml.example
src/config.rs

Address the failures reported by our CI system.
They were caused by two changes done to the `policies.yml` file parsing:
- The usage of `deny_unknown_fields` with untagged `Enum` is affected by a bug inside of the `serde` library. This is a known issue
- The `policies.yml.example` file had invalid contents

fix policies yml parsing

---

Cargo.lock
Cargo.toml
src/lib.rs
tests/integration_test.rs

When running on Linux, monitor changes done to the TLS certificate and key used by the https server.
When both change, react by updating the TLS configuration.
This allows to rotate the TLS certificate used by a Policy Server without having to restart the process.
Notes:
- This is not covered by the unit tests right now. I don't know yet how hard it would be to test it. I'll leave a comment here once I know more about the topic
- This change is part of the upcoming work to handle certificate rotation inside of the whole KW stack
- Ideally, we can merge this code right now and make it part of the 1.15 release since it won't cause any harm

feat: automatic TLS certificate reload

---

Cargo.lock
Cargo.toml
src/tracing.rs

Updates the OpenTelemetry version in use to v0.24.

chore(deps): bump OpenTelemetry version to 0.24.

---

Cargo.lock
Cargo.toml

Bumps the version in the Cargo files to v1.15.0-rc1

chore: bump v1.15.0-rc1.

---

src/config.rs

Due to the recent addition of policy groups, the parsing of policies.yml was broken.
This happened because of [a pretty confusing serde behavior](https://github.com/serde-rs/json/issues/501), as an attribute on an enum is renaming all the variants of the enum, not all the fields of those variants.
TODO:

fix: policies.yml parsing

---

Cargo.lock
Cargo.toml
src/evaluation/precompiled_policy.rs

build: Bump version to v1.15.0-rc2

---

hack/docker-compose.yml
src/metrics.rs

Fixes: #847 
`opentelemetry-otlp` v.0.17.0 [introduces a breaking change](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-otlp/CHANGELOG.md), we need to call `global::set_meter_provider(meter_provider.clone());.` after building the metric provider. 
This PR fixes it.
We tested it locally with the dev tracing/metrics `docker-compose` and it seems to fix the issue.

fix: call set_meter_provider 

---

Cargo.lock
Cargo.toml
Makefile
tests/common/mod.rs
tests/data/otel-collector-config.yaml
tests/integration_test.rs

Adds otel collector integration test.
The otelc container is started using  `testcontainers`, and configured with file exporters.
We can then read and parse the file contents and assert that everything is fine.
Fixes: #855

test: add otelc integration test

---

Cargo.lock
Cargo.toml
src/main.rs
tests/integration_test.rs

Starting from the 0.22 release, rustls requires each application to configure its default crypto provider. Without that, the application will face a runtime panic.
This is something the "cert-reload" integration test allowed us to expose.

fix: properly configure rustls stack

---

Dockerfile

Fix building the docker image locally.
Addresses https://github.com/kubewarden/policy-server/issues/846

fix: allow Docker image to be built locally

---

.github/workflows/release.yml

Adds the read access to the "contents" permission in the release
workflow. This is necessary to allow the workflow to run. Otherwise, the
release job will not start.
Signed-off-by: José Guilherme Vanz <jguilhermevanz@suse.com>

fix(ci): container build permissions in release workflow.

---

Cargo.lock
Cargo.toml

* fix: address Sigstore's TUF repository changes. The Sigstore's TUF repository changed format, causing the verification capabilities to break. This commit bumps the `policy-evaluator` crate, which brings a patched version of `sigstore-rs` as dependency.
* Update a bunch of dependencies, including `quinn-proto`, which has been impacted by a security issue.

fix: address changes to Sigstore's TUF repository

---

.cargo/audit.toml

A bunch of warnings have popped up. There's nothing we can do about them and they basically no impact on us.
- "RUSTSEC-2024-0370": This is a warning about `proc-macro-errors` being unmaintained. It's a transitive dependency of `sigstore` and `oci-spec`.
- "RUSTSEC-2023-0055": This is a warning about `lexical` having multiple soundness issues. It's a transitive dependency of `sigstore`.

chore: update cargo audit ignore list

---

Cargo.lock
Cargo.toml
src/api/service.rs
src/evaluation/evaluation_environment.rs
tests/integration_test.rs

The API Server puts some limitations on the warnings:
- they cannot exceed 256 characters
- the size of all the warnings cannot exceed 4096 characters
- they are returned as HTTP headers, hence not all characters are allowed
Because of these reasons, starting from now, we use the warning struct only to tell the user whether a member policy was evaluated or not. When it was evaluated we just tell the outcome (allow/reject).
The details of each policy evaluation are returned as part of the `AdmissionResponse.status.details.causes`.
Notes: the warning messages are always shown, regardless of the request being accepted or rejected.
The `AdmissionResponse.status.details.causes` are shown only when the request is rejected. `kubectl` shows them only when run with verbose major or equal to 4 …

fix: revisit AdmissionResponse of policy groups

---

Cargo.toml
src/lib.rs
tests/integration_test.rs

When detecting certificate and key changes, rely on the proper inotify message.
We have to wait for the `CLOSE_WRITE` event to happen to be sure all the contents of the cert/key have been written and flushed to disk.
Otherwise there's the risk of loading some incomplete data, leading to a runtime panic.
This was detected thanks to a flaky test.

fix: make cert rotation detection more reliable

---

tests/integration_test.rs

Sporadically, the `test_otel` integration test fails in the CI (see #916). 
However, this proved to be hard to reproduce locally. 
For this reason, we are adding the full output as a custom message to the failing assertion, so we can debug the flakiness in a later step.

test: add json output as otel assertions custom message 

---

src/evaluation/evaluation_environment.rs
tests/integration_test.rs

While testing the group policy feature, it was realized that the warning messages returned by the policy groups can be confusing. This commit changes the code to stop adding warnings with the evaluation results from policy members.
Fix #927

fix: remove warnings from policy groups.

---

Cargo.lock
Cargo.toml

Bumps `opentelemetry*` to `v0.26.0` and `tracing-opentelemetry` to `v0.27.0`

build(deps): bump opentelemetry dependencies to v0.26.0

---

src/cli.rs
src/config.rs
src/main.rs
src/metrics.rs
src/tracing.rs
tests/common/mod.rs
tests/integration_test.rs

This PR adds a new `--otlp-endpoint` flag and the `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable, allowing users to specify a custom gRPC OTLP endpoint for exporting both metrics and traces.
Part of #993 
Updates existing integration tests.

feat: add otlp endpoint config and cli flag

---

README.md
policies.yml.example
src/config.rs
src/evaluation/evaluation_environment.rs
src/policy_downloader.rs
tests/common/mod.rs
tests/integration_test.rs

Renames the "url" field into "module". This makes the field name the same of the name used in the CRDs.
Fix #906

fix!: renames "url" field into "module".

---

Cargo.lock
Cargo.toml
Dockerfile

build: Bump version to 1.21.0-rc1, Dockerfile changes

---

Dockerfile

[By default, the `Cargo.lock` file that is included with the package will be ignored by `cargo install`.](https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile)
Since the Dockerfile uses `cargo auditable install`, there were scenarios where the build regenerated `Cargo.lock` with updated dependencies.  
As a result, the CI passed while the Docker build failed (see [[GitHub Actions run](https://github.com/kubewarden/policy-server/actions/runs/12902609277/job/35976498867)](https://github.com/kubewarden/policy-server/actions/runs/12902609277/job/35976498867)).  
This PR updates the Dockerfile to add `--locked` to the `cargo auditable install` instruction, fixing the issue.

fix: cargo install ignoring Cargo.lock

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
Makefile
README.md
cli-docs.md
src/cli.rs
src/main.rs

Adds the "docs" subcommand to allow the CLI reference documentation generation in markdown format.
Related to #810

feat(cli): generate CLI reference documentation.

---

Cargo.lock
Cargo.toml

The contents of Sigstore's TUF repository have been recently changed and, due to a mistake, the sigstore-rs was broken.
This commit consumes a forked version of sigstore-rs, which consumes a forked version of the tough crate.
This is required to fix https://github.com/sigstore/sigstore-rs/issues/429 until upstream changes the contents of TUF's repository.

fix: address broken sigstore's TUF repository

---

src/lib.rs

When a panic occurs in a `tokio::spawn` block, it only terminates the specific task while allowing the main program to continue execution. Currently, the hot-reload functionality uses `expect()`, which means any issues with a certificate or key validation will cause the hot-reload mechanism to stop working. 
This pull request replaces the panic with error logging so that the hot-reload task will keep running.

fix: do not panic in certificate hot-reload task

---

Cargo.lock
Cargo.toml

Upgrade to latest version of sigstore by consuming latest stable release of policy-evaluator.

chore(deps): update sigstore

---

cli-docs.md
src/cli.rs
src/config.rs
src/lib.rs
tests/common/mod.rs
tests/integration_test.rs

Fix: #1077
Splits the api and the readiness server in two axum servers running on different ports.
[tokio::Notify](https://docs.rs/tokio/latest/tokio/sync/struct.Notify.html) was used to start serving the readiness probe server right after the main API server.

feat: expose readiness probe over http

---

cli-docs.md
src/cli.rs
src/config.rs
src/lib.rs
tests/integration_test.rs

With the latest changes, `TlsConfig` was always set to `Some`, causing the policy server to attempt loading certificate files from the default CLI value, which was an empty string (`""`). As a result, the policy server failed to start.  
This PR introduces an additional validation step:  
1. If either the certificate or key is provided while the other is missing.
2. If neither a certificate nor a key is provided via flags, `TlsConfig` is set to `None`.  
3. If a client CA is specified but the certificate and key are missing, an error is raised.  
The rationale behind point 3 is that mTLS is only enabled when server certificates are configured.

fix: TlsConfig and mTLS logic

---

.taplo.toml
Cargo.lock
Cargo.toml

This PR consumes latest version of policy-evaluator. I just wanted to make sure some of the changes done to its public API are not breaking anything in this repo. 
While at that, I've also added the usual taplo configuration to format our `Cargo.toml` file

chore(deps): update policy-evaluator

---

src/cli.rs
src/config.rs
src/lib.rs
tests/integration_test.rs

Updates the policy server to allow loading multiple CA to validate the certificate used by client in a mTLS scenario.
Fix #1078 
```shell
make test
```

feat: multiple client CA.

---

src/certs.rs
src/config.rs
src/lib.rs
tests/integration_test.rs

Fix: #1091
This PR resolves a race condition that occurs during TLS certificate reloads by retaining the previous certificate and key pair if the client CA file changes. This approach enables reloading the server certificate and client CA independently.
Additionally, it replaces blocking std::fs functions within async blocks with their asynchronous counterparts from tokio::fs.

fix: remove TLS hot-reload race condition

---

src/cli.rs

After the recent changes clap is not able to cast the CLI flags into PathBuf type. To fix that, we can configure the value parser when the Arg is created.
This is causing errors when running CI on Kubewarden controller main branch and https://github.com/kubewarden/kubewarden-controller/pull/1007
```console
KUBEWARDEN_CERT_FILE="tls.crt" KUBEWARDEN_KEY_FILE="tls.key" KUBEWARDEN_POLICIES_DOWNLOAD_DIR=/tmp KUBEWARDEN_POLICIES=policies.yml.example KUBEWARDEN_LOG_LEVEL=debug KUBEWARDEN_SIGSTORE_CACHE_DIR="/tmp/sigstore-data" KUBEWARDEN_ALWAYS_ACCEPT_ADMISSION_REVIEWS_ON_NAMESPACE="kubewarden" KUBEWARDEN_CLIENT_CA_FILE="ca.crt" cargo run
thread 'main' panicked at src/config.rs:193:29:
Mismatch between definition and access of `cert-file`. Could not downcast to std::path::PathBuf, need to …
```

fix: clap cannot downcast CLI flags to PathBuf

---

Cargo.lock
Cargo.toml
tests/integration_test.rs

Prepare for 1.22.0-rc1 release

---

.github/workflows/ci.yml

On release (when the CI workflow is triggered by a tag), check that the Cargo.toml `version` matches the tag.
This prevents releasing badly tagged or version-annotated images.
This is lifted from kwctl's CI.
Tested locally.

ci: Add version-check job to check Cargo.toml on release

---

.github/workflows/ci.yml
.typos.toml
Makefile
src/api/service.rs
src/config.rs
src/evaluation/evaluation_environment.rs
src/evaluation/precompiled_policy.rs
src/policy_downloader.rs
src/profiling.rs
tests/common/mod.rs
tests/integration_test.rs

Use `crate-ci/typos` to detect typos

test: detect typos

---

Dockerfile
cli-docs.md
src/cli.rs

The default value used by by readiness probe http server must be different from the one used to expose the validation endpoints. Having the same port causes the process to fail because two webservers are trying to bind to the same port.
Port 3000 is still used by default to expose the actual validation endpoints, while port 8081 is used to expose the readiness probe endpoint.
By default the Policy Server does not enforce TLS on its main port, because of that using a default value of 8443 instead of 3000 would lead to some confusion (assuming https has to be used instead of http).
To be honest, this is not relevant for the Kubewarden stack, since the kubewarden-controller has always been tuning the PolicyServer deployment to use port 8443. This is more useful for developers and for users …

fix: change default readiness probe port

---

Cargo.lock
Cargo.toml

build: Bump version to 1.23.0-beta2

---

src/tracing.rs

fix: removed the rustls=off filter directive, which was previously suppressing all TLS-related message

---

Cargo.lock
Cargo.toml
src/evaluation/errors.rs
src/evaluation/evaluation_environment.rs

The code that deals with policy groups has now been moved into policy-evaluator to make it reusable to kwctl.

refactor: policy group

---

.github/workflows/release.yml

Part of https://github.com/kubewarden/kubewarden-controller/issues/1099.
Tagged a `v1.24.0-viccuad` from my fork, which run:
https://github.com/viccuad/policy-server/actions/runs/14730283408

ci: Substitute peter-evans/repository-dispatch with gh cli

---

rust-toolchain.toml

Updates the rust-toolchain.toml file adding the missing targets which the policy server is build for.

fix: add missing rust toolchain targets.

---

policies.yml.example
src/api.rs
src/api/admission_response_handler.rs
src/api/service.rs
src/config.rs
src/evaluation/evaluation_environment.rs
src/evaluation/policy_evaluation_settings.rs
tests/common/mod.rs
tests/integration_test.rs

Updates the policy server to allow user define a "message" field in the policies.yml file to customize the error message returned by the policy.
Fix #1190

feat: custom error message support.

---

Cargo.lock
Cargo.toml
tests/integration_test.rs

In a recent change policy-evaluator change the error message for the timeout evaluation error. This commit fixes the integration test to consider this new error message
Depends on https://github.com/kubewarden/policy-evaluator/pull/769
```shell
make integration-tests
```

fix(test): update timeout evaluation error message
